### ISSUE TITLE
License for use

### ISSUE THREAD

**Issue by galtroarc** [yinonavraham/GoogleAppsScripts#4]
Hi there. I would like to use the EnhancedCacheService code in my commercial project . Is there a license this code is under or am I free to use this with attribution?

Very useful stuff. Thank you!

**Comment by yinonavraham** [comment]
Hi @galtroarc,

Thanks for the feedback.
You can feel free to use it, I intended it to be under the MIT license, just forgot to mention... 
I will add the license soon.

Enjoy!

**Comment by galtroarc** [comment]
Thanks much @yinonavraham .

**Comment by galtroarc** [comment]
@yinonavraham if you don't mind @ mentioning me in this issue once you do add the license, I will include it in my code as well.
